-- Excel file name CZS_VendBankAccount

WITH Ranked AS (
  SELECT
    '' AS BANKCODETYPE,
    RIGHT([bs].BANKOVNI_UCET, 5) AS ACCOUNTID,
    bs.NAZEV AS NAME,
    st.ZKRATKA AS COUNTRYREGIONID,
    bs.BANKOVNI_UCET AS ACCOUNTNUM,
    afv.ZKRATKA AS VENDACCOUNT,
    '' AS SWIFTNO,
    '' AS BANKGROUPID,
    bs.IBAN AS BANKIBAN,
    'CZS' AS DATAAREAID,
    bs.UID AS LEGACYKEY,
    ROW_NUMBER() OVER (
      PARTITION BY RIGHT(bs.BANKOVNI_UCET, 5), afv.ZKRATKA
      ORDER BY bs.UID DESC
    ) AS rn
  FROM AdresarFirem afv
  JOIN BankovniSpojeni bs ON afv.UID = bs.LINK_UID
  LEFT JOIN Stat st ON afv.STAT_UID = st.UID
  WHERE afv.AKTIVNI = 'True' AND afv.ZKRATKA LIKE 'D%' AND bs.BANKOVNI_UCET != ''
)
SELECT 
  BANKCODETYPE,
  ACCOUNTID,
  NAME,
  COUNTRYREGIONID,
  ACCOUNTNUM,
  VENDACCOUNT,
  SWIFTNO,
  BANKGROUPID,
  BANKIBAN,
  DATAAREAID,
  LEGACYKEY
FROM Ranked
WHERE rn = 1;